name: Laravel API Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: Create .env file
      run: |
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=production" >> .env
        echo "APP_KEY=" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "APP_URL=http://your-ec2-public-ip" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
    
    - name: Generate app key
      run: php artisan key:generate
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ubuntu
      run: |
        # Save private key and set permissions
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        
        # Test SSH connection
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "echo 'SSH connection successful'"
        
        # Ensure target directory exists
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "sudo mkdir -p /var/www/laravel-api && sudo chown $USER:$USER /var/www/laravel-api"
        
        # Use rsync to avoid copying .git and other unnecessary files
        rsync -avz --exclude='.git' --exclude='node_modules' --exclude='storage' -e "ssh -i private_key" ./ $USER@$HOST:/var/www/laravel-api
        
        # Ensure .env is set up
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << EOF
          cd /var/www/laravel-api
          if [ ! -f .env ]; then
            cp .env.example .env
          fi
          composer install
          php artisan migrate
          php artisan config:clear
          php artisan cache:clear
          sudo systemctl restart nginx
        EOF
        
    - name: Set permissions for web server
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "sudo chown -R www-data:www-data /var/www/laravel-api && sudo chmod -R 775 /var/www/laravel-api"
