name: Laravel API Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Install Dependencies
      runщення

    run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: Create .env file
      run: |
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=production" >> .env
        echo "APP_KEY=" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "APP_URL=http://your-ec2-public-ip" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
    
    - name: Generate app key
      run: php artisan key:generate
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ubuntu
      run: |
        # Save private key and set permissions
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        
        # Test SSH connection
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "echo 'SSH connection successful'"
        
        # Ensure target directory exists
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "sudo mkdir -p /var/www/laravel-api && sudo chown $USER:$USER /var/www/laravel-api"
        
        # Add PHP PPA and install PHP 8.2 with MySQL extension
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "sudo apt-get update && sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get update && sudo apt-get install -y php8.2 php8.2-mysql"
        
        # Ensure MySQL is running on EC2
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "sudo systemctl start mysql && sudo systemctl status mysql"
        
        # Clean up existing .git directory and set permissions recursively
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "sudo rm -rf /var/www/laravel-api/.git && sudo chown -R $USER:$USER /var/www/laravel-api"
        
        # Copy files to EC2
        scp -o StrictHostKeyChecking=no -i private_key -r . $USER@$HOST:/var/www/laravel-api
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << EOF
          cd /var/www/laravel-api
          cp .env.example .env  # Ensure .env is copied on the server
          composer install
          php artisan migrate
          php artisan config:clear
          php artisan cache:clear
          sudo systemctl restart nginx
          
          # Debug NGINX failure if it occurs
          sudo systemctl status nginx.service || journalctl -xeu nginx.service
        EOF