- name: Deploy to EC2
  env:
    PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    HOST: ${{ secrets.EC2_HOST }}
    USER: ubuntu
  run: |
    # Save private key and set permissions
    echo "$PRIVATE_KEY" > private_key
    chmod 600 private_key
    
    # Test SSH connection
    ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "echo 'SSH connection successful'"
    
    # Ensure the target directory exists and set permissions
    ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST "
      sudo mkdir -p /var/www/laravel-api && 
      sudo chown $USER:$USER /var/www/laravel-api
    "
    
    # Copy files to EC2
    scp -o StrictHostKeyChecking=no -i private_key -r . $USER@$HOST:/var/www/laravel-api